Basic build mk
KSU-Mobile-Dev-Club/Calculator pull request #1
Opened 2021-10-13 23:09 UTC by mkeith1064

Functional build, does not consider order of operations.

2021-10-13 23:20 UTC, awbooze commented on .idea/deploymentTargetDropDown.xml
> +<?xml version="1.0" encoding="UTF-8"?>
.idea folder really should be in the gitignore - I don't know why it isn't by default.

2021-10-13 23:53 UTC, awbooze requested changes
Looks good overall! Only minor changes needed.

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +        val btntext : String? = btn?.text.toString()
btntext is always non-null, so you don't need to have the question mark on "String?"

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +    fun buttonPress(view: android.view.View) {
You don't need to qualify View if you've already imported it up-top.

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +        var x : Int = 1
This doesn't need to have an explicit type (although it can, and I probably would include it here).

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +import kotlin.math.roundToInt
Some unneeded imports here.

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +        display.setText(this.equation)
Every instance of this could be replaced with display.text = this.equation in order to be more like typical Kotlin.

2021-10-13 23:53 UTC, awbooze commented on app/src/main/res/layout/activity_main.xml
> +    <Button
It'll be worth increasing the button size later, but not now, necessarily.

2021-10-13 23:53 UTC, awbooze commented on app/src/main/java/edu/ksu/cs/mdc/calculator/MainActivity.kt
> +    private fun convertToMath(equation: String): List<String> {
I like the way you broke this up into multiple functions. You might even be able to just use convertToMath in order to add in order of operations without modifying anything else.

2021-10-20 23:14 UTC, jhpleimann approved these changes
I approve

2021-10-20 23:14 UTC, awbooze approved these changes

2021-10-20 23:15 UTC, merged